name: Bonjour
on:
  - push
  - pull_request
jobs:
  dire_bonjour:
    runs-on: ubuntu-22.04
    steps:
      - run: ls -l # Liste les fichier du répertoire courant
      - name: Check out main
        uses: actions/checkout@v3
      - name: Read README.md
        id: readme
        uses: juliangruber/read-file-action@v1
        with:
          path: ./README.md
      - name: output the message on actions result
        uses: Code-Hex/neo-cowsay-action@v1
        with:
          message: ${{ steps.readme.outputs.content }}
      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: 3.8.6
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: 17.0.6
      - run: mvn -v
      - run: mvn compile
      - run: ls -ltra ./target
      - run: mvn package
      - run: ls -ltra ./target
    