name: Bonjour
on:
  - push
jobs:
  dire_bonjour:
    runs-on: ubuntu-22.04
    steps:
      - run: ls -l # Liste les fichier du répertoire courant
      - name: Check out main
        uses: actions/checkout@v3
      - run: |
          sudo apt-get update
          sudo apt-get install cowsay -y
      - run: cat README.md | cowsay # Affiche le contenu du fichier `README.md` à la base du dépôt
